CREATE TABLE IF NOT EXISTS `itb_scratch_box` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`TITLE` varchar(255) NOT NULL,
	`CREATION_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATOR_ID` int NOT NULL,
	`AMOUNT` double NOT NULL DEFAULT 0,
	`COUNT` int NOT NULL DEFAULT 0,
	`COMMENT` varchar(255) NULL,
	PRIMARY KEY(`ID`),
	FOREIGN KEY (CREATOR_ID) REFERENCES b_user(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `itb_scratch_thing` (
	`ID` int NOT NULL AUTO_INCREMENT,
	`BOX_ID` int NOT NULL,
	`NAME` varchar(255) NOT NULL,
	`DESCRIPTION` varchar(255) NULL,
	`CREATION_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATOR_ID` int NOT NULL,
	`VALUE` double NOT NULL DEFAULT 0,
	`IS_TRASH` varchar(1) NOT NULL DEFAULT 'N',
	`COMMENT` varchar(255) NULL,
	PRIMARY KEY(`ID`),
	FOREIGN KEY (CREATOR_ID) REFERENCES b_user(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (BOX_ID) REFERENCES itb_scratch_box(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

