CREATE TABLE IF NOT EXISTS `itb_mike_book` (
    `ID_BOOK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`ID_PUBLISHER` INT(10) UNSIGNED NOT NULL,
	`ID_AUTHOR` INT(10) UNSIGNED NOT NULL,
    `TITLE` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATE_AT` DATETIME NOT NULL DEFAULT 0,
    `UPDATE_AT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_BOOK)
);

CREATE TABLE IF NOT EXISTS `itb_mike_publisher` (
    `ID_PUBLISHER` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME_COMPANY` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATE_AT` DATETIME NOT NULL DEFAULT 0,
    `UPDATE_AT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_PUBLISHER)
);

CREATE TABLE IF NOT EXISTS `itb_mike_author` (
    `ID_AUTHOR` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATE_AT` DATETIME NOT NULL DEFAULT 0,
    `UPDATE_AT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_AUTHOR)
);