CREATE TABLE IF NOT EXISTS `itb_mike_book` (
    `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`IDPUBLISHER` INT(10) UNSIGNED NOT NULL,
	`IDAUTHOR` INT(10) UNSIGNED NOT NULL,
    `TITLE` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATEAT` DATETIME NOT NULL DEFAULT 0,
    `UPDATEAT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `itb_mike_publisher` (
    `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAMECOMPANY` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATEAT` DATETIME NOT NULL DEFAULT 0,
    `UPDATEAT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS `itb_mike_author` (
    `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATEAT` DATETIME NOT NULL DEFAULT 0,
    `UPDATEAT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);