CREATE TABLE IF NOT EXISTS `itb_mike_book` (
    `IDBOOK` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`IDPUBLISHER` INT(10) UNSIGNED NOT NULL,
	`IDAUTHOR` INT(10) UNSIGNED NOT NULL,
    `TITLE` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATEAT` DATETIME NOT NULL DEFAULT 0,
    `UPDATEAT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (IDBOOK)
);

CREATE TABLE IF NOT EXISTS `itb_mike_publisher` (
    `IDPUBLISHER` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAMECOMPANY` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATEAT` DATETIME NOT NULL DEFAULT 0,
    `UPDATEAT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (IDPUBLISHER)
);

CREATE TABLE IF NOT EXISTS `itb_mike_author` (
    `IDAUTHOR` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(128) NOT NULL DEFAULT '',
    `CREATEAT` DATETIME NOT NULL DEFAULT 0,
    `UPDATEAT` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (IDAUTHOR)
);