CREATE TABLE IF NOT EXISTS `itb_service_mail_domain` (
    `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `ACTIVE` VARCHAR(1) NOT NULL DEFAULT 'Y' ,
    `DOMAIN` VARCHAR(128) NOT NULL DEFAULT '' ,
    `SERVER` VARCHAR(128) NOT NULL DEFAULT '' ,
    `PORT` INT NOT NULL,
    PRIMARY KEY (ID)
);